services:
  web:
    container_name: markt-web
    tty: true
    build:
      context: ./markt-web/
      dockerfile: Dockerfile
    volumes:
      - ${MARKT_WEB_PATH}:/var/www/html
    depends_on:
      - api
    networks:
      - markt
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
  api:
    container_name: markt-api
    tty: true
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    build:
      context: ./markt-api
      dockerfile: Dockerfile
    volumes:
      - ${MARKT_API_PATH}:/var/www/html
    depends_on:
      - mariadb
    networks:
      - markt
    configs:
      - source: php_config
        target: /usr/local/etc/php/conf.d/99-app.ini
      - source: xdebug_config
        target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - source: fpm_config
        target: /usr/local/etc/php-fpm.d/www.conf
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
  mariadb:
    container_name: markt-mariadb
    image: mariadb:lts
    ports:
      - 127.0.0.1:13306:3306/tcp
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_password
    volumes:
      - mariadb:/var/lib/mysql:rw
    configs:
      - source: mariadb_init
        target: /docker-entrypoint-initdb.d/init_db.sh
        mode: 777
    networks:
      - markt
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 127.0.0.1:8080:80/tcp
    networks:
      - markt
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - web
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          cpus: "0.12"
          memory: 64M
volumes:
  mariadb:
    driver: local
networks:
  markt:
    driver: bridge
secrets:
   db_password:
     environment: "DB_PASSWORD"
configs:
  xdebug_config:
    file: ./markt-api/xdebug.ini
  php_config:
    file: ./markt-api/php.ini
  fpm_config:
    file: ./markt-api/www.conf
  mariadb_init:
    file: ./mariadb/init_db.sh
  nginx_config:
    file: ./nginx/default.conf